services:
  # Live DBMS for automatic models generation.
  postgres:
    image: postgres:17
    container_name: postgres-dbms
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - 5432:5432
    command: >
      -c fsync=off
      -c full_page_writes=off
      -c transaction_isolation=serializable
    volumes:
      - ./postgresql:/var/lib/postgresql
